apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kubectl-configmap
  name: kubectl-configmap
spec:
  containers:
    - image: config-demo:latest
      name: config-demo
      ports:
        - containerPort: 8080
      imagePullPolicy: IfNotPresent
      env:
        - name: TEST_ID
          valueFrom:
            configMapKeyRef:
              name: test-config
              key: test-id
        - name: TEST_PW
          valueFrom:
            configMapKeyRef:
              name: test-config
              key: test-pw
  restartPolicy: Never